Fixing clashing naming of temp directories
sharkdp/fd pull request #1194
Opened 2022-12-01 13:41 UTC by Ptipiak

## Objective
* The random names of temporay directories used for test are clashing witht the actual test
* Fixes #1181 

## Solution
* using 2 bytes for naming the directories

2022-12-01 17:28 UTC, tmccombs requested changes
cargo fmt needs to be run, but other than that, this looks ok to me.

2022-12-01 18:15 UTC, tavianator commented
I think two bytes is not enough.  I can reliably make individual test cases take more than 1 minute just by running a couple copies of the test suite at once, as my `/tmp` fills up with `fd-tests??` directories.

This also doesn't fix the problem that the tests fail 100% of the time when run from e.g. `/home/dirk/fd`.

Instead I think we need to change our test cases to use names that can't be generated by `tempfile` (e.g. by using symbols), and that also aren't likely to show up in normal paths.

2022-12-03 12:47 UTC, Ptipiak commented
I think it should be the temp file generation which should provide a way to avoid certain sub-string in the genreated names.
Would it be possible to use a pre-defined set of directory names as random name for `tempfile`? This way we could make sure non of the randomly choosen names would clash with the tests

2022-12-05 15:20 UTC, tavianator commented
I believe #1200 supersedes this.  Thank you for the contribution!  It's always great to be able to try multiple approaches.

2022-12-05 15:20 UTC, closed without merging