Gitignore workaround
sharkdp/fd pull request #1521
Opened 2024-03-14 05:48 UTC by tmccombs

2024-04-28 21:19 UTC, tavianator requested changes
I think this workaround is incomplete: we should do the same thing if the user passes `.` as a path explicitly.

It's also worth adding a test case I think.

2024-04-30 08:00 UTC, tavianator approved these changes

2024-04-30 13:55 UTC, sharkdp commented on CHANGELOG.md
> +- Fix bug that would cause hidden files to be includeddespite gitignore rules
minor
```suggestion
- Fix bug that would cause hidden files to be included despite gitignore rules
```

2024-04-30 13:56 UTC, sharkdp approved these changes
Thank you!

2024-04-30 13:56 UTC, merged