Change time comparisons to exclusive by default, add `--time-inclusive`
sharkdp/fd pull request #821
Opened 2021-08-09 12:14 UTC by jacobmischka

As the names imply, `--change-newer-than` and `--change-before` now are
exclusive (`>` or `<`) by default. A new flag `--time-inclusive`
(aliased to simply `--inclusive`) is added to opt into the previous
inclusive (`>=` or `<=`) behavior.

Fixes #794

2021-08-31 04:57 UTC, tmccombs requested changes
I'm also not entirely sure if we need the `--time-inclusive` option.

2021-08-31 04:57 UTC, tmccombs commented on doc/fd.1
> +Files with modification times greater the argument will be returned.
I don't think the `than` should be removed from this sentence.

```suggestion
Files with modification times greater than the argument will be returned.
```

2021-11-14 15:44 UTC, sharkdp commented
I haven't followed the discussion in #794 closely. Can the bug be fixed without introducing a new command-line option? @jacobmischka are you still interested to work on this?

2021-11-15 08:10 UTC, tmccombs commented
> Can the bug be fixed without introducing a new command-line option? 

I think so. The new command line option is if we want to keep a way to use an inclusive range, but I'm not really sure if that is needed.

2021-11-15 08:20 UTC, jacobmischka commented
Sure, though if we don't want to keep the existing behavior with a flag this PR is probably not worth revising, since all that's left then is to remove two `=` characters. I can do that, if that's the route we want to go.

2021-11-15 08:25 UTC, sharkdp commented
> Sure, though if we don't want to keep the existing behavior with a flag this PR is probably not worth revising, since all that's left then is to remove two `=` characters. I can do that, if that's the route we want to go.

I would prefer this. Any help would be very much appreciated.

2021-11-17 08:56 UTC, closed without merging

2021-11-17 08:56 UTC, jacobmischka commented
I made a new PR since it was frankly just easier to start from master. #886